### PR TITLE
Issue66 with ci-skip parameter

### LINKED ISSUE #66: CI option
Hello,

I would like the release to trigger CI as in my worklow, the CI is actually generating the artifacts of the release.
It would be nice to have a CI option in order to trigger CI or not just like semantic-release offer:
https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#ci
It would then either add "[ci skip] ***NO_CI***" or not.

I believe so far it is not possible ?

Thanks

### PR DESCRIPTION
**Pull request by FranzNieschalk**
Continuing the work of @Biboba, I checked out his `issue66` branch, addressing your feedback from #67: 

- updated README
- renamed parameter to `ci-skip`
- set default of parameter to `false`

Hope it closes #66, we need this feature desperately.

### CODE REVIEW

**Comment by leonardoanalista** [comment]
Thanks again for the PR! I merged and changed the a braking change if you don't mind. The default true could affect existing users upgrading to this version.

**Comment by FranzNieschalk** [comment]
@leonardoanalista Thank you for accepting and merging this PR. Could you release these changes on npm?

**Comment by leonardoanalista** [comment]
Think this didn’t get released again. I’ll need to look at this issue in the next few days

**Comment by FranzNieschalk** [comment]
@leonardoanalista Bumping for new release (sorry for that).

**Pull request merged**
