### PR TITLE
feat(app): tagPrefix

### PR DESCRIPTION
**Pull request by tmosest**
users can add a prefix string to the version tags

ISSUES CLOSED: #58

### CODE REVIEW

**Comment by tmosest** [comment]
@leonardoanalista hey should I merge this?

**Comment by leonardoanalista** [comment]
It looks good to me.

**Comment by taiichiro-nagase** [comment]
@leonardoanalista 
Hi.
I'd like to use this feature. when does this PR publish?

**Comment by leonardoanalista** [comment]
PR has been merged. It should be in the latest version 👍

**Comment by taiichiro-nagase** [comment]
Hmm, the latest version is 6.4.0, isn’t it?
it seems 6.4.0 is not contained this feature.

I think it may need to `npm publish`.

**Comment by taiichiro-nagase** [comment]
@leonardoanalista excuse me.
how do you think about this?

**Comment by leonardoanalista** [comment]
The PR introducing this feature has been merged. I can see the unit tests. Maybe the feature is not working as expected. Did you add the appropriated options to your config file? I'll investigate this when I have a chance ok?

**Comment by taiichiro-nagase** [comment]
@leonardoanalista hmm, in other word, why don’t you release `corp-semantic-release@6.5.0` that includes this feature.

**Comment by patrickvaler** [comment]
Hi @leonardoanalista, could you please do a new release which contains this feature? As already mentioned it isn't available within v6.4.0:
https://github.com/leonardoanalista/corp-semantic-release/blob/v6.4.0/src/index.js

**Comment by leonardoanalista** [comment]
@patrickvaler Yes, travis.ci is not releasing anything. It looks like we are using an old version or semantic-release v7. We should upgrade to v.15. There could be breaking changes to be addressed.

**Comment by leonardoanalista** [comment]
I am going to upgrade semantic-release now and let you know.

**Comment by leonardoanalista** [comment]
@patrickvaler I hope it works now. It was the npm `2fa` configuration issues. It should release from Travis from now on.

**Comment by patrickvaler** [comment]
@leonardoanalista thanks a lot. With v6.5.0 the tagPrefix option works as expected!

**Pull request merged**
