### PR TITLE
feat(app): add flag to commit to signal VSTS CI servers to ignore the…

### PR DESCRIPTION
**Pull request by marceloavf**
… commit

This avoid VSTS CI servers running another build due to changes related to versioning

ISSUES CLOSED: #54

### CODE REVIEW

**Comment by marceloavf** [comment]
It should help, I only discovered this function after the first test, would it be good to include it in the FAQ section?

There is an issue in [vsts-agent #858](https://github.com/Microsoft/vsts-agent/issues/858), I really need this to continue my work in VSTS, since it's building twice, I'll open another issue there talking about it there.

**Comment by leonardoanalista** [comment]
Sure! I merge it now then we track vsts issue. We update readme in separate pr

**Comment by marceloavf** [comment]
Okay, waiting for the release to test it out, thanks!

**Comment by leonardoanalista** [comment]
It’s supposed to release automatically after every commit merged into master. I don’t know why it didn’t release. I’ll have to investigate tomorrow

**Comment by marceloavf** [comment]
No problem, this should help https://github.com/semantic-release/semantic-release/issues/347

**Comment by marceloavf** [comment]
Seems that the node 8 version have to be the build leader to publish, or use some build stages to make it work properly

**Pull request merged**
